spring:
  application:
    name: buggloo
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  web:
    resources:
      add-mappings: false
  
server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    dev.stroe.buggloo: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o
  max-tokens: 2048

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized 